# -*- coding: utf-8 -*-
"""Copy of CodeAlpha_Stock_Portfolio_Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xtf4Wih2_gfTYpRkwv-rH2m-spkOVzg8
"""

# Stock Portfolio Tracker
# CodeAlpha Python Programming Internship - Task 2

# Indian stock prices (example prices)
stock_prices = {
    "RELIANCE": 1400,
    "TCS": 4000,
    "INFY": 1800,
    "HDFCBANK": 1700,
    "ITC": 500
}

print("===================================")
print("     STOCK PORTFOLIO TRACKER")
print("===================================")

print("\nAvailable Stocks:")

for stock in stock_prices:
    print(stock, "₹", stock_prices[stock])

# Ask how many stocks the user wants to add
number_of_stocks = int(input("\nHow many different stocks do you want to add? "))

total_investment = 0

# Store user's portfolio
portfolio = {}

for i in range(number_of_stocks):

    stock = input("\nEnter stock name: ").upper()

    # Check if stock is available
    if stock not in stock_prices:
        print("Stock not available.")
        continue

    quantity = int(input("Enter quantity: "))

    investment = stock_prices[stock] * quantity

    portfolio[stock] = quantity
    total_investment += investment

    print("Investment in", stock, "=", "₹", investment)

# Display portfolio
print("\n===================================")
print("          YOUR PORTFOLIO")
print("===================================")

for stock in portfolio:
    print(stock, "-", portfolio[stock], "shares")

print("\nTotal Investment = ₹", total_investment)
print("===================================")